-- MySQL Script generated by MySQL Workbench
-- Mon Jan 29 17:18:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema books
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema books
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `books` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema world
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema world
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `world` DEFAULT CHARACTER SET latin1 ;
USE `books` ;

-- -----------------------------------------------------
-- Table `books`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `books`.`authors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `books`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `books`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`id`, `author_id`),
  INDEX `fk_books_authors1_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_books_authors1`
    FOREIGN KEY (`author_id`)
    REFERENCES `books`.`authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `books`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `books`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `books`.`favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `books`.`favorites` (
  `user_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `book_id`),
  INDEX `fk_users_has_books_books1_idx` (`book_id` ASC) VISIBLE,
  INDEX `fk_users_has_books_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_books_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `books`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_books_books1`
    FOREIGN KEY (`book_id`)
    REFERENCES `books`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `world` ;

-- -----------------------------------------------------
-- Table `world`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `world`.`countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` CHAR(3) NOT NULL DEFAULT '',
  `name` CHAR(52) NOT NULL DEFAULT '',
  `continent` ENUM('Asia', 'Europe', 'North America', 'Africa', 'Oceania', 'Antarctica', 'South America') NOT NULL DEFAULT 'Asia',
  `region` CHAR(26) NOT NULL DEFAULT '',
  `surface_area` FLOAT(10,2) NOT NULL DEFAULT '0.00',
  `indep_year` SMALLINT NULL DEFAULT NULL,
  `population` INT NOT NULL DEFAULT '0',
  `life_expectancy` FLOAT(3,1) NULL DEFAULT NULL,
  `gnp` FLOAT(10,2) NULL DEFAULT NULL,
  `gnp_old` FLOAT(10,2) NULL DEFAULT NULL,
  `local_name` CHAR(45) NOT NULL DEFAULT '',
  `government_form` CHAR(45) NOT NULL DEFAULT '',
  `head_of_state` CHAR(60) NULL DEFAULT NULL,
  `capital` INT NULL DEFAULT NULL,
  `code2` CHAR(2) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 240
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `world`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `world`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` CHAR(35) NOT NULL DEFAULT '',
  `country_code` CHAR(3) NOT NULL DEFAULT '',
  `district` CHAR(20) NOT NULL DEFAULT '',
  `population` INT NOT NULL DEFAULT '0',
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cities_countries1_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_cities_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `world`.`countries` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4080
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `world`.`languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `world`.`languages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country_code` CHAR(3) NOT NULL DEFAULT '',
  `language` CHAR(30) NOT NULL DEFAULT '',
  `is_official` ENUM('T', 'F') NOT NULL DEFAULT 'F',
  `percentage` FLOAT(4,1) NOT NULL DEFAULT '0.0',
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_languages_countries_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_languages_countries`
    FOREIGN KEY (`country_id`)
    REFERENCES `world`.`countries` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 985
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
